# Netlify Build Configuration

[build]
  # Command to build the entire project (frontend and backend functions)
  # 1. Install root dependencies (for frontend, and workspace installs if any)
  # 2. Build frontend (output to 'dist')
  # 3. Install server dependencies
  # 4. Build backend server (output to 'server/dist')
  # 5. Build Netlify function(s) (e.g., from 'netlify/functions/' to 'netlify/functions_build/')
  command = "npm install && npm run build && cd server && npm install && npm run build && cd .. && npm run build:functions"

  # Directory containing the frontend static assets after build
  publish = "dist"

  # Directory containing compiled serverless functions
  # This directory will be created by our 'build:functions' script
  functions = "netlify/functions_build"

[build.environment]
  # Set Node.js version for build and functions.
  # Check your project's package.json engines field or use a recent LTS.
  NODE_VERSION = "18"
  # For AWS Lambda runtime for functions (alternative to NODE_VERSION for functions)
  # AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

# Redirect rule for API calls to Netlify functions
# All requests to /api/* will be proxied to the 'api' function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 # OK status for proxying

# Redirect rule for Single Page Applications (SPA)
# This ensures that direct navigation to frontend routes (e.g., /profile)
# serves the index.html, allowing React Router to handle routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Plugin for managing redirects from a _redirects file if preferred
# [[plugins]]
#   package = "@netlify/plugin-redirects"
